import pptxgen from "pptxgenjs";

export const generatePPTX = async (dashData, activeExclusionCodes, auditVerdicts) => {
  // 1. Initialize PPTX
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_16x9"; // 10 x 5.625 inches
  pptx.author = "Akurat-iDRG System";
  pptx.company = "Faskes";
  pptx.subject = "Laporan Analitik Eksekutif JKN";
  pptx.title = "Laporan Klaim JKN";

  // Shared formatting
  const titleProps = { x: 0.5, y: 0.4, w: "90%", h: 0.5, color: "0f172a", fontSize: 24, bold: true, fontFace: "Arial" };
  const subProps = { x: 0.5, y: 0.9, w: "90%", h: 0.3, color: "64748b", fontSize: 14, fontFace: "Arial" };
  const tableHeaderProps = { fill: "0d9488", color: "ffffff", bold: true, fontFace: "Arial", fontSize: 10, align: "center", valign: "middle" };
  const tableCellProps = { fontFace: "Arial", fontSize: 9, valign: "middle", border: { pt: 1, color: "e2e8f0" } };

  // Helper to format Rp
  const formatRp = (val) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(val);

  // ---------------------------------------------------------------------------
  // SLIDE 1: COVER
  // ---------------------------------------------------------------------------
  const slideCover = pptx.addSlide();
  slideCover.background = { fill: "0d9488" }; // Teal 600
  
  slideCover.addText("LAPORAN ANALITIK EKSEKUTIF JKN", { x: 1, y: 2, w: 8, fontSize: 36, bold: true, color: "ffffff", align: "center", fontFace: "Arial" });
  slideCover.addText("Generated by Akurat-iDRG", { x: 1, y: 3, w: 8, fontSize: 18, color: "ccfbf1", align: "center", fontFace: "Arial" });
  slideCover.addText(`Tanggal Generate: ${new Date().toLocaleDateString('id-ID')}`, { x: 1, y: 3.5, w: 8, fontSize: 12, color: "99f6e4", align: "center", fontFace: "Arial" });


  // ---------------------------------------------------------------------------
  // SLIDE 2: DASHBOARD RINGKASAN
  // ---------------------------------------------------------------------------
  let totalPasien = 0;
  let totalTarifRS = 0;
  let totalTarifINA = 0;
  let totalLoss = 0;
  let totalGain = 0;
  let totalSelisih = 0;
  let lossGains = [];

  if (dashData && dashData.rawRows) {
    const rawRows = dashData.rawRows;
    totalPasien = rawRows.length;


    rawRows.forEach(r => {
      const rs = parseFloat(r.TARIF_RS || r.BIAYA_RS || r.TOTAL_TARIF_RS || 0) || 0;
      const ina = parseFloat(r.TOTAL_TARIF || 0) || 0;
      const selisih = ina - rs;

      totalTarifRS += rs;
      totalTarifINA += ina;
      if (selisih < 0) totalLoss += selisih;
      if (selisih > 0) totalGain += selisih;

      lossGains.push({
        sep: String(r.SEP || '-'),
        nama: String(r.NAMA_PASIEN || r.NAMA_PASien || r.NAMA || '-'),
        inacbg: String(r.INACBG || '-'),
        tarifRs: rs,
        tarifIna: ina,
        selisih: selisih
      });
    });

    totalSelisih = totalTarifINA - totalTarifRS;

    const sc = dashData.scorecard;
    const slideDash = pptx.addSlide();
    
    slideDash.addText("Ringkasan Eksekutif Klaim JKN", titleProps);
    slideDash.addText("Overview Kinerja Finansial", subProps);

    // Scorecard Boxes
    const boxW = 4;
    const boxH = 0.8;
    
    // Total Kasus
    slideDash.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.5, w: boxW, h: boxH, fill: "f8fafc", line: { color: "e2e8f0", pt: 1 } });
    slideDash.addText("TOTAL KASUS", { x: 0.6, y: 1.6, w: boxW-0.2, fontSize: 10, color: "64748b", bold: true });
    slideDash.addText(`${totalPasien.toLocaleString()} Pasien`, { x: 0.6, y: 1.9, w: boxW-0.2, fontSize: 16, color: "0f172a", bold: true });

    // Selisih Tarif
    slideDash.addShape(pptx.ShapeType.rect, { x: 5, y: 1.5, w: boxW, h: boxH, fill: totalSelisih >= 0 ? "ecfdf5" : "fff1f2", line: { color: totalSelisih >= 0 ? "a7f3d0" : "fecdd3", pt: 1 } });
    slideDash.addText("NET SELISIH (INA/iDRG - RS)", { x: 5.1, y: 1.6, w: boxW-0.2, fontSize: 10, color: totalSelisih >= 0 ? "059669" : "e11d48", bold: true });
    slideDash.addText(`${totalSelisih >= 0 ? '+' : ''}${formatRp(totalSelisih)}`, { x: 5.1, y: 1.9, w: boxW-0.2, fontSize: 16, color: totalSelisih >= 0 ? "065f46" : "9f1239", bold: true });

    // Potensi Loss & Gain
    slideDash.addShape(pptx.ShapeType.rect, { x: 0.5, y: 2.5, w: boxW, h: boxH, fill: "fff1f2", line: { color: "fecdd3", pt: 1 } });
    slideDash.addText("POTENSI KERUGIAN (LOSS)", { x: 0.6, y: 2.6, w: boxW-0.2, fontSize: 10, color: "e11d48", bold: true });
    slideDash.addText(`${formatRp(totalLoss)}`, { x: 0.6, y: 2.9, w: boxW-0.2, fontSize: 16, color: "9f1239", bold: true });

    slideDash.addShape(pptx.ShapeType.rect, { x: 5, y: 2.5, w: boxW, h: boxH, fill: "ecfdf5", line: { color: "a7f3d0", pt: 1 } });
    slideDash.addText("POTENSI KEUNTUNGAN (GAIN)", { x: 5.1, y: 2.6, w: boxW-0.2, fontSize: 10, color: "059669", bold: true });
    slideDash.addText(`${formatRp(totalGain)}`, { x: 5.1, y: 2.9, w: boxW-0.2, fontSize: 16, color: "065f46", bold: true });

    // Total Tarif RS vs INA
    slideDash.addShape(pptx.ShapeType.rect, { x: 0.5, y: 3.5, w: boxW, h: boxH, fill: "f1f5f9", line: { color: "e2e8f0", pt: 1 } });
    slideDash.addText("TOTAL TARIF RS", { x: 0.6, y: 3.6, w: boxW-0.2, fontSize: 10, color: "475569", bold: true });
    slideDash.addText(`${formatRp(totalTarifRS)}`, { x: 0.6, y: 3.9, w: boxW-0.2, fontSize: 16, color: "334155", bold: true });

    slideDash.addShape(pptx.ShapeType.rect, { x: 5, y: 3.5, w: boxW, h: boxH, fill: "f0fdfa", line: { color: "ccfbf1", pt: 1 } });
    slideDash.addText("TOTAL TARIF INA / iDRG", { x: 5.1, y: 3.6, w: boxW-0.2, fontSize: 10, color: "0d9488", bold: true });
    slideDash.addText(`${formatRp(totalTarifINA)}`, { x: 5.1, y: 3.9, w: boxW-0.2, fontSize: 16, color: "115e59", bold: true });
  }

  // ---------------------------------------------------------------------------
  // SLIDE 3: TOP 10 KASUS LOSS TERBESAR
  // ---------------------------------------------------------------------------
  if (lossGains && lossGains.length > 0) {
    const losses = lossGains.filter(c => c.selisih < 0).sort((a, b) => a.selisih - b.selisih).slice(0, 10);
    
    if (losses.length > 0) {
      const slideLoss = pptx.addSlide();
      slideLoss.addText("Top 10 Kasus Loss Terbesar", titleProps);
      slideLoss.addText("Berdasarkan selisih Tarif INA - Tarif RS", subProps);

      const tableRows = [
        [
          { text: "No", options: tableHeaderProps },
          { text: "SEP", options: tableHeaderProps },
                    { text: "INA CBG", options: tableHeaderProps },
          { text: "Tarif RS", options: tableHeaderProps },
          { text: "Tarif INA", options: tableHeaderProps },
          { text: "Selisih Loss", options: tableHeaderProps }
        ]
      ];

      losses.forEach((c, idx) => {
        tableRows.push([
          { text: String(idx + 1), options: { ...tableCellProps, align: "center" } },
          { text: c.sep || "-", options: tableCellProps },
                    { text: c.inacbg || "-", options: { ...tableCellProps, align: "center" } },
          { text: formatRp(c.tarifRs), options: { ...tableCellProps, align: "right" } },
          { text: formatRp(c.tarifIna), options: { ...tableCellProps, align: "right" } },
          { text: formatRp(c.selisih), options: { ...tableCellProps, align: "right", color: "e11d48", bold: true } }
        ]);
      });

      slideLoss.addTable(tableRows, { x: 0.5, y: 1.5, w: 4.5, colW: [0.3, 0.9, 0.8, 0.9, 0.8, 0.8] });

      const chartData = [
        {
          name: "Selisih Loss (Rp)",
          labels: losses.map(c => String(c.inacbg || '-')),
          values: losses.map(c => Math.abs(c.selisih))
        }
      ];
      slideLoss.addChart(pptx.ChartType.bar, chartData, { x: 5.2, y: 1.5, w: 4.5, h: 3.5, barDir: 'bar', showLegend: false, dataLabelColor: '000000', showValue: true, valAxisHidden: true, catAxisLabelColor: '333333', chartColors: ['e11d48'] });

    }
  }


  // ---------------------------------------------------------------------------
  // SLIDE 4 & 5: AUDIT KODING
  // ---------------------------------------------------------------------------
  if (dashData && dashData.auditFindings && dashData.auditFindings.length > 0) {
    // Audit Insight Summary
    const slideAuditSum = pptx.addSlide();
    slideAuditSum.addText("Audit Koding - Ringkasan", titleProps);
    
    const totalFindings = dashData.auditFindings.length;
    let sesuai = 0;
    let tidakSesuai = 0;
    let belum = 0;

    dashData.auditFindings.forEach(f => {
      const key = `${f.sep}|${f.ruleId}`;
      const verdict = auditVerdicts[key];
      if (verdict === 'sesuai') sesuai++;
      else if (verdict === 'tidak') tidakSesuai++;
      else belum++;
    });

    const accuracy = (sesuai + tidakSesuai) > 0 ? (sesuai / (sesuai + tidakSesuai) * 100).toFixed(1) : "100.0";

    slideAuditSum.addText(`Total Temuan Audit: ${totalFindings}`, { x: 0.5, y: 1.5, w: 4, fontSize: 16, bold: true, color: "0f172a" });
    slideAuditSum.addText(`- Sesuai: ${sesuai}`, { x: 0.5, y: 2.0, w: 4, fontSize: 14, color: "059669" });
    slideAuditSum.addText(`- Tidak Sesuai: ${tidakSesuai}`, { x: 0.5, y: 2.4, w: 4, fontSize: 14, color: "e11d48" });
    slideAuditSum.addText(`- Belum Review: ${belum}`, { x: 0.5, y: 2.8, w: 4, fontSize: 14, color: "64748b" });
    slideAuditSum.addText(`Skor Akurasi Koder: ${accuracy}%`, { x: 0.5, y: 3.4, w: 4, fontSize: 18, bold: true, color: "0d9488" });

    // Table Data
    const tableRows = [
      [
        { text: "No", options: { ...tableHeaderProps, fill: "0f172a" } },
        { text: "SEP", options: { ...tableHeaderProps, fill: "0f172a" } },
        { text: "Rule ID", options: { ...tableHeaderProps, fill: "0f172a" } },
        { text: "Temuan / Kasus", options: { ...tableHeaderProps, fill: "0f172a" } },
        { text: "Warning Message", options: { ...tableHeaderProps, fill: "0f172a" } },
        { text: "Status", options: { ...tableHeaderProps, fill: "0f172a" } }
      ]
    ];

    dashData.auditFindings.forEach((f, idx) => {
      const key = `${f.sep}|${f.ruleId}`;
      const verdict = auditVerdicts[key] || 'Belum';
      const statusText = verdict === 'sesuai' ? 'Sesuai' : verdict === 'tidak' ? 'Tidak Sesuai' : 'Belum Review';
      
      tableRows.push([
        { text: String(idx + 1), options: { ...tableCellProps, align: "center" } },
        { text: f.sep || "-", options: tableCellProps },
        { text: f.ruleId || "-", options: { ...tableCellProps, align: "center", bold: true } },
        { text: f.case || "-", options: tableCellProps },
        { text: f.warning || "-", options: { ...tableCellProps, fontSize: 8 } }, // Smaller text for warning
        { text: statusText, options: { ...tableCellProps, align: "center", bold: true, color: verdict === 'sesuai' ? "059669" : verdict === 'tidak' ? "e11d48" : "64748b" } }
      ]);
    });

    // Auto-paginating table for findings
    const slideAuditTable = pptx.addSlide();
    slideAuditTable.addText("Detail Temuan Audit Koding", titleProps);
    slideAuditTable.addTable(tableRows, { 
      x: 0.5, y: 1.2, w: 9.0, 
      colW: [0.4, 1.4, 1.0, 2.0, 3.2, 1.0], 
      autoPage: true, 
      autoPageRepeatHeader: true,
      autoPageLineWeight: 0,
      margin: 0.1
    });
  }

  // ---------------------------------------------------------------------------
  // SLIDE 6 & 7: PENDING SAKTI
  // ---------------------------------------------------------------------------
  if (dashData && dashData.pendingSakti && dashData.pendingSakti.length > 0) {
    const slidePS = pptx.addSlide();
    slidePS.addText("Pending SAKTI - Ringkasan", titleProps);

    const total = dashData.pendingSakti.length;
    let internal = 0, eksternal = 0, belumReview = 0;
    
    dashData.pendingSakti.forEach(p => {
      if (p.faktor === 'Internal RS') internal++;
      else if (p.faktor === 'Eksternal BPJS') eksternal++;
      else belumReview++;
    });

    slidePS.addText(`Total Kasus Pending: ${total}`, { x: 0.5, y: 1.5, w: 4, fontSize: 16, bold: true, color: "0f172a" });
    slidePS.addText(`- Internal RS: ${internal}`, { x: 0.5, y: 2.0, w: 4, fontSize: 14, color: "e11d48" });
    slidePS.addText(`- Eksternal BPJS: ${eksternal}`, { x: 0.5, y: 2.4, w: 4, fontSize: 14, color: "0284c7" });
    slidePS.addText(`- Belum Teridentifikasi: ${belumReview}`, { x: 0.5, y: 2.8, w: 4, fontSize: 14, color: "64748b" });

    // Pending Table
    const tableRows = [
      [
        { text: "No", options: { ...tableHeaderProps, fill: "334155" } },
        { text: "SEP", options: { ...tableHeaderProps, fill: "334155" } },
        { text: "Nama Pasien", options: { ...tableHeaderProps, fill: "334155" } },
        { text: "Keterangan Pending", options: { ...tableHeaderProps, fill: "334155" } },
        { text: "Kelompok", options: { ...tableHeaderProps, fill: "334155" } },
        { text: "Faktor Penyebab", options: { ...tableHeaderProps, fill: "334155" } }
      ]
    ];

    dashData.pendingSakti.forEach((c, idx) => {
      const kat = Array.isArray(c.kategori) ? c.kategori.join(', ') : (c.kategori || '-');
      tableRows.push([
        { text: String(idx + 1), options: { ...tableCellProps, align: "center" } },
        { text: c.sep || "-", options: tableCellProps },
                { text: c.keterangan || "-", options: { ...tableCellProps, fontSize: 8 } },
        { text: kat, options: { ...tableCellProps, align: "center" } },
        { text: c.faktor || "-", options: { ...tableCellProps, align: "center", bold: true } }
      ]);
    });

    const slidePSTable = pptx.addSlide();
    slidePSTable.addText("Detail Pending SAKTI", titleProps);
    slidePSTable.addTable(tableRows, { 
      x: 0.5, y: 1.2, w: 9.0, 
      colW: [0.4, 1.4, 1.6, 2.8, 1.4, 1.4], 
      autoPage: true, 
      autoPageRepeatHeader: true,
      margin: 0.1
    });
  }

  // ---------------------------------------------------------------------------
  // SLIDE 8: KPI CODER
  // ---------------------------------------------------------------------------
  if (dashData && dashData.kpiCoderArray && dashData.kpiCoderArray.length > 0) {
    const tableRows = [
      [
        { text: "No", options: { ...tableHeaderProps, fill: "0369a1" } },
        { text: "ID Coder", options: { ...tableHeaderProps, fill: "0369a1" } },
        { text: "Total Kasus", options: { ...tableHeaderProps, fill: "0369a1" } },
        { text: "Temuan Audit", options: { ...tableHeaderProps, fill: "0369a1" } },
        { text: "Discrepancy (INA vs iDRG)", options: { ...tableHeaderProps, fill: "0369a1" } }
      ]
    ];

    dashData.kpiCoderArray.forEach((c, idx) => {
      tableRows.push([
        { text: String(idx + 1), options: { ...tableCellProps, align: "center" } },
        { text: c.id || "-", options: { ...tableCellProps, bold: true } },
        { text: String(c.cases || 0), options: { ...tableCellProps, align: "center" } },
        { text: String(c.auditHits || 0), options: { ...tableCellProps, align: "center", color: c.auditHits > 0 ? "e11d48" : "0f172a" } },
        { text: String(c.discrepancyCount || 0), options: { ...tableCellProps, align: "center", color: c.discrepancyCount > 0 ? "e11d48" : "0f172a" } }
      ]);
    });

    const slideKPI = pptx.addSlide();
    slideKPI.addText("KPI & Kinerja Coder", titleProps);
    slideKPI.addText("Berdasarkan Volume Kasus dan Tingkat Akurasi", subProps);
    
    slideKPI.addTable(tableRows, { 
      x: 0.5, y: 1.5, w: 9.0, 
      colW: [0.5, 3.0, 1.5, 2.0, 2.0], 
      autoPage: true, 
      autoPageRepeatHeader: true,
      margin: 0.1
    });
  }

  // ---------------------------------------------------------------------------
  // SAVE PPTX
  // ---------------------------------------------------------------------------
  return pptx.writeFile({ fileName: `Laporan_Analitik_Akurat_${new Date().getTime()}.pptx` });
};


export const generateSosialisasiPPTX = async ({ ksmName, ksmStats, topCases, topUpPotentials, scatterImageBase64, quadrantInsights }) => {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_16x9";
  pptx.author = "Akurat-iDRG System";
  pptx.subject = "Laporan Sosialisasi KMKB";
  pptx.title = "Sosialisasi KSM " + ksmName;

  const titleProps = { x: 0.5, y: 0.4, w: "90%", h: 0.5, color: "0f172a", fontSize: 24, bold: true, fontFace: "Arial" };
  const subProps = { x: 0.5, y: 0.9, w: "90%", h: 0.3, color: "64748b", fontSize: 14, fontFace: "Arial" };
  const tableHeaderProps = { fill: "0d9488", color: "ffffff", bold: true, fontFace: "Arial", fontSize: 10, align: "center", valign: "middle" };
  const tableCellProps = { fontFace: "Arial", fontSize: 9, valign: "middle", border: { pt: 1, color: "e2e8f0" } };
  const formatRp = (val) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(val);

  // 1. COVER SLIDE
  const slideCover = pptx.addSlide();
  slideCover.background = { fill: "0d9488" };
  slideCover.addText("LAPORAN SOSIALISASI & EVALUASI KMKB", { x: 1, y: 2, w: 8, fontSize: 32, bold: true, color: "ffffff", align: "center" });
  slideCover.addText("KSM: " + ksmName.toUpperCase(), { x: 1, y: 2.8, w: 8, fontSize: 24, bold: true, color: "ccfbf1", align: "center" });
  slideCover.addText("Tanggal: " + new Date().toLocaleDateString('id-ID'), { x: 1, y: 3.5, w: 8, fontSize: 14, color: "99f6e4", align: "center" });

  // 2. RINGKASAN FINANSIAL KSM
  const slideFin = pptx.addSlide();
  slideFin.addText("Ringkasan Kinerja - KSM " + ksmName, titleProps);
  slideFin.addText("Evaluasi Finansial dan Volume Kasus", subProps);

  slideFin.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.5, w: 4, h: 1, fill: "f8fafc", line: { color: "e2e8f0", pt: 1 } });
  slideFin.addText("Total Kasus KSM", { x: 0.6, y: 1.6, w: 3.8, fontSize: 12, color: "64748b", bold: true });
  slideFin.addText(ksmStats.kasus.toLocaleString() + " Kasus", { x: 0.6, y: 2.0, w: 3.8, fontSize: 20, color: "0f172a", bold: true });

  slideFin.addShape(pptx.ShapeType.rect, { x: 5.0, y: 1.5, w: 4, h: 1, fill: "f1f5f9", line: { color: "e2e8f0", pt: 1 } });
  slideFin.addText("Total Tarif INA-CBG", { x: 5.1, y: 1.6, w: 3.8, fontSize: 12, color: "64748b", bold: true });
  slideFin.addText(formatRp(ksmStats.ina), { x: 5.1, y: 2.0, w: 3.8, fontSize: 20, color: "0f172a", bold: true });

  slideFin.addShape(pptx.ShapeType.rect, { x: 0.5, y: 3.0, w: 4, h: 1, fill: ksmStats.selisih >= 0 ? "ecfdf5" : "fff1f2", line: { color: ksmStats.selisih >= 0 ? "a7f3d0" : "fecdd3", pt: 1 } });
  slideFin.addText("Net Selisih (INA - RS)", { x: 0.6, y: 3.1, w: 3.8, fontSize: 12, color: ksmStats.selisih >= 0 ? "059669" : "e11d48", bold: true });
  slideFin.addText((ksmStats.selisih >= 0 ? '+' : '') + formatRp(ksmStats.selisih), { x: 0.6, y: 3.5, w: 3.8, fontSize: 20, color: ksmStats.selisih >= 0 ? "065f46" : "9f1239", bold: true });

  slideFin.addShape(pptx.ShapeType.rect, { x: 5.0, y: 3.0, w: 4, h: 1, fill: "fff1f2", line: { color: "fecdd3", pt: 1 } });
  slideFin.addText("Total Potensi Loss", { x: 5.1, y: 3.1, w: 3.8, fontSize: 12, color: "e11d48", bold: true });
  slideFin.addText(formatRp(ksmStats.loss), { x: 5.1, y: 3.5, w: 3.8, fontSize: 20, color: "9f1239", bold: true });

  // 3. SCATTER PLOT & INSIGHTS
  if (scatterImageBase64) {
    const slideScatter = pptx.addSlide();
    slideScatter.addText("Analisis Kuadran KMKB - KSM " + ksmName, titleProps);
    slideScatter.addText("Posisi INA-CBG berdasarkan Volume dan Selisih", subProps);
    
    slideScatter.addImage({ data: scatterImageBase64, x: 0.5, y: 1.3, w: 5.2, h: 4 });

    slideScatter.addText("Rekomendasi Sosialisasi & Evaluasi:", { x: 6.0, y: 1.3, w: 3.6, fontSize: 14, bold: true, color: "0f172a" });
    let yPos = 1.7;
    quadrantInsights.forEach(qi => {
      slideScatter.addText(qi, { x: 6.0, y: yPos, w: 3.6, fontSize: 11, color: "334155", bullet: true });
      yPos += 0.8;
    });
  }

  // 4. TOP KASUS DEFISIT
  if (topCases && topCases.length > 0) {
    const slideTop = pptx.addSlide();
    slideTop.addText("Top INA-CBG Defisit - KSM " + ksmName, titleProps);
    slideTop.addText("10 Kasus penyumbang kerugian terbesar", subProps);

    const tableRows = [
      [
        { text: "No", options: tableHeaderProps },
        { text: "INA CBG", options: tableHeaderProps },
        { text: "Kasus", options: tableHeaderProps },
        { text: "Total Loss", options: tableHeaderProps }
      ]
    ];

    const chartData = [
      {
        name: "Total Loss (Rp)",
        labels: topCases.map(c => String(c.cbg || '-')),
        values: topCases.map(c => Math.abs(c.loss))
      }
    ];

    topCases.forEach((c, idx) => {
      tableRows.push([
        { text: String(idx + 1), options: { ...tableCellProps, align: "center" } },
        { text: c.cbg || "-", options: { ...tableCellProps, align: "center", bold: true } },
        { text: String(c.count || 0), options: { ...tableCellProps, align: "center" } },
        { text: formatRp(c.loss), options: { ...tableCellProps, align: "right", color: "e11d48", bold: true } }
      ]);
    });

    slideTop.addTable(tableRows, { x: 0.5, y: 1.5, w: 4.8, colW: [0.3, 1.3, 0.8, 2.4] });
    slideTop.addChart(pptx.ChartType.bar, chartData, { x: 5.5, y: 1.5, w: 4.0, h: 3.5, barDir: 'bar', showLegend: false, showValue: true, valAxisHidden: true, chartColors: ['e11d48'] });
  }

  // 5. POTENSI TOP-UP
  if (topUpPotentials && topUpPotentials.length > 0) {
    const tableRows = [
      [
        { text: "No", options: tableHeaderProps },
        { text: "INA CBG Lama", options: tableHeaderProps },
        { text: "Potensi INA CBG (Top-Up)", options: tableHeaderProps },
        { text: "Kriteria Klinis Tambahan", options: tableHeaderProps },
        { text: "Perkiraan Delta Tarif", options: tableHeaderProps }
      ]
    ];

    topUpPotentials.forEach((c, idx) => {
      tableRows.push([
        { text: String(idx + 1), options: { ...tableCellProps, align: "center" } },
        { text: c.oldCbg || "-", options: { ...tableCellProps, align: "center" } },
        { text: c.newCbg || "-", options: { ...tableCellProps, align: "center", bold: true, color: "059669" } },
        { text: c.kriteria || "-", options: tableCellProps },
        { text: formatRp(c.delta), options: { ...tableCellProps, align: "right", bold: true, color: "059669" } }
      ]);
    });

    const slideTopUp = pptx.addSlide();
    slideTopUp.addText("Potensi Top-Up (Severity Level) - KSM " + ksmName, titleProps);
    slideTopUp.addTable(tableRows, { 
      x: 0.5, y: 1.2, w: 9.0, 
      colW: [0.4, 1.6, 1.6, 3.4, 2.0], 
      autoPage: true, 
      autoPageRepeatHeader: true,
      margin: 0.1
    });
  }

  return pptx.writeFile({ fileName: 'Sosialisasi_KSM_' + ksmName.replace(/\s+/g, '_') + '_' + new Date().getTime() + '.pptx' });
};
